baseurl = "/"
languageCode = "en-US"
title = "fyteaching"
# theme = "hugo-lithium"
googleAnalytics = ""
# ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Books"
    url = "/books/index.html"
    weight = 2
[[menu.main]]
    name = "MA 321"
    url = "/ma321/index.html"
    weight = 3
[[menu.main]]
    name = "MA 336"
    url = "/ma336/index.html"
    weight = 4
[[menu.main]]
    name = "Others"
    url = "/others/index.html"
    weight = 5
# [[menu.main]]
#     name = "GitHub"
#     url = "https://github.com/rstudio/blogdown"
# [[menu.main]]
#     name = "Twitter"
#     url = "https://twitter.com/rstudio"

[params]
    description = "A website for teaching/learning in math."

    # options for highlight.js (version, additional languages, and theme)
    # highlightjsVersion = "9.12.0"
    # highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    # highlightjsLang = ["r", "yaml"]
    # highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    # favicon = "favicon.ico"

    # [params.logo]
    # url = "logo.png"
    # width = 50
    # height = 50
    # alt = "Logo"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
    unsafe = true  # Enable user to embed HTML snippets in Markdown content.
  [markup.highlight]
    codeFences = false