baseurl = "/"
# relativeURLs = true
# canonifyURLs = true

languageCode = "en-US"
title = "MathTR"
# theme = "hugo-lithium"
# googleAnalytics = ""
# ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Books"
    url = "/books/"
    weight = 1
[[menu.main]]
    name = "Slides"
    url = "/slides/"
    weight = 2
[[menu.main]]
    name = "Labs"
    url = "/labs/"
    weight = 3
[[menu.main]]
    name = "Reviews"
    url = "/refs/"
    weight = 4
[[menu.main]]
    name = "Worksheets"
    url = "/worksheets/"
    weight = 5
[[menu.main]]
    name = "Learning Goals"
    url = "/goals/"
    weight = 6
[[menu.main]]
    name = "Misc"
    url = "/misc/"
    weight = 7

[params]
    description = "A website for teaching in math."

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    # favicon = "favicon.ico"

    # [params.logo]
    # url = "logo.png"
    # width = 50
    # height = 50
    # alt = "Logo"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
    unsafe = true  # Enable user to embed HTML snippets in Markdown content.
  [markup.highlight]
    codeFences = false
