# https://github.com/actions/starter-workflows/blob/main/pages/hugo.yml
name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - master
      # to be able to trigger a manual build
    workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: |
          hugo --minify
      
      - name: Deploy 🚀
        # only deploy when push to main
        # if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # The branch the action should deploy to.
          branch: gh-pages
          # The folder the action should deploy. Adapt if you changed in Quarto config
          folder: public
